# Generated by Django 2.0.2 on 2018-05-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('tileid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opaqueCloud', models.IntegerField()),
                ('thinCloud', models.IntegerField()),
                ('thickCloud', models.IntegerField()),
                ('land', models.IntegerField()),
                ('water', models.IntegerField()),
                ('snow', models.IntegerField()),
            ],
        ),
    ]
