# Generated by Django 2.0.2 on 2018-05-03 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='imagetile',
            name='filename',
        ),
        migrations.AddField(
            model_name='imagetile',
            name='fileid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='game.ImageFile'),
            preserve_default=False,
        ),
    ]
