# Generated by Django 2.0.2 on 2018-05-04 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180503_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetile',
            name='userScore',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='game.Score'),
            preserve_default=False,
        ),
    ]
