# Generated by Django 2.0.2 on 2018-05-04 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_imagetile_userscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagetile',
            name='userScore',
        ),
        migrations.AddField(
            model_name='imagetile',
            name='score',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='machineScore', to='game.Score'),
            preserve_default=False,
        ),
    ]
